export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const AUTHORIZED_USER = 'AUTHORIZED_USER';
export const LOGOUT = 'LOGOUT';

export const GET_USER_DIALOGUES = 'GET_USER_DIALOGUES';